### PR TITLE
Types fixes 2

### PR DESCRIPTION
**Pull request by StoneCypher**

### CODE REVIEW

**Comment by StoneCypher** [comment]
I'm sorry this took me so long.  (Listen to this blues song about my life)

Thank you for this generous donation, @tylerbutler

**Comment by StoneCypher** [comment]
Released as `5.100.0`.  There's a `5.101` inbound on some library bumps

**Comment by tylerbutler** [comment]
> I'm sorry this took me so long. (Listen to this blues song about my life)
> 
> Thank you for this generous donation, @tylerbutler

Thanks a lot for merging this! The new release of jssm seems to work for us.

While upgrading, I noticed that jssm-viz is exhibiting a similar problem - I addressed it in a similar way to my changes here, and the patched version works in our repo. I will open a PR against jssm-viz shortly for you to take a look.

**Comment by tylerbutler** [comment]
> I will open a PR against jssm-viz shortly for you to take a look.

@StoneCypher The PR I mentioned: https://github.com/StoneCypher/jssm-viz/pull/54

**Comment by tylerbutler** [comment]
@StoneCypher Also, I want to apologize for the "meaningless" commits in this PR. I was operating in "squash merge" mode and did not clean up the commit history like I should have for a standard merge. Sorry for the clutter.

**Comment by StoneCypher** [comment]
I actually prefer unsquashed

Thank you for the donations

**Comment by tylerbutler** [comment]
> Thank you for the donations

You're welcome. Happy to contribute. :) Thanks for the great library.

**Pull request merged**
